export const locations = [
  "Aalapot, Kageshwari, Halapur",
  "Aanppipal, Bhorle, Jaljale, Sunodumre, Pachchyan",
  "Aarupokhari, ",
  "Alampu, and Bigu VDC, Orang VDC, Babare VDC, Gumba",
  "Atarpur, ",
  "Baad Bhanjyang, ",
  "Baad Bhanjyang, Mabina",
  "Badegau, Majhi Gaun",
  "Badikhel, ",
  "Badikhel, and also Godawari VDC",
  "Bahrabise, Thulopalati",
  "Balkumari, and also Samundratar VDC",
  "Baluwa, Tokha",
  "BanepaN.P., Aashapuri",
  "Baruwa, Yarsa/Bhothang/Yangri/Bolgun",
  "Bhaktapur, ",
  "Bhaktapur, Durlang",
  "BhaktapurN.P., ",
  "BhaktapurN.P., Dattataray Square",
  "BhaktapurN.P., Dattatraya",
  "BhaktapurN.P., Durlang",
  "BhaktapurN.P., Pottery Square",
  "Bhanu, Turture",
  "Bhardev, ",
  "Bhardev, Bhardeudeldanda",
  "Bhattedanda, ",
  "Bhattedanda, Tinpane",
  "Bhattedanda, and also Malta VDC",
  "BhimesworN.P., Sakine",
  "Bhorle, ",
  "Bhorle, wards 1 to 9",
  "Bhulbhule, ",
  "BidurN.P., Battar",
  "BidurN.P., Devighat ward 7",
  "Bigu, wards 7 & 8",
  "Bridhim, ",
  "Budhakhani, ",
  "Bukhel, and also Choughare VDC",
  "Bulung, Bhirmundi",
  "Bungamati, ",
  "Bungamati, and also Lubhu VDC",
  "ChandeniMandan, Chandeni/Davagaon - ward 6",
  "Chapagaun, Bista Gaun",
  "Chapagaun, Ghyampedanda",
  "Chapagaun, Jhalungtar",
  "Chapagaun, Neupanegaun",
  "ChauriKharka, ",
  "Chhaimale, ",
  "ChhatreDyaurali, ",
  "ChhatreDyaurali, Ramche, Maidan, wards 2, 4, 7, 9",
  "ChhatreDyaurali, ward 1 & 3",
  "Chhetrapa, Yabo",
  "Chhetrapa, Yobo village",
  "Chhoprak, Cheuri",
  "Chhoprak, Gaira, Jaisithok, Phirphire, Arubot, ward 8",
  "Chilankha, ward 9 - by car to Sifal, then helicopter drop off to Chilankha (Minu Silwal 014490516",
  "Chisapani, Rayale",
  "Choukati, ",
  "Choukati, Lungurpa, Dandagaun, Pandali",
  "Chuchure, For distribution details see: https://docs.google.com/document/d/1ztdIUnVq0GfZg5M4u3fuxnBlkhOxtyGYaz58dUslMeo/edit?usp=sharing",
  "Chuchure, Shivalaya village",
  "Chumchet, Domje Chumba Lungdang - helicopter drop off",
  "Chunikhel, ",
  "Dalchoki, ",
  "Darbhung, Rampur ward 8 - Distribution details see: https://docs.google.com/document/d/1Jgm-EVR1fAek-OnKr3A6nHK6rIxU2E_8aY6LeCZiDY4/edit?usp=sharing",
  "Devichour, ",
  "Devichour, and also Dhusel, Chhampi, Dukuchhap",
  "Dhawa, Chautara",
  "Dhola, Chedi/Guthgaun/Dhuaga/Dhuwako",
  "DhulikhelN.P, Kutal",
  "DhulikhelN.P, Sindhu, Listi, Chansingh",
  "DhulikhelN.P, Thakuri",
  "Dhuyang, ",
  "Dhuyang, Deurali Chalasi ward 6",
  "Dhuyang, Ghumtang, Dandagaun, Kolbari, Kimbegaun, Khanyabas, Devchagaun, Chapleti",
  "Dhuyang, Jhyamling, Ghimpche",
  "Dhuyang, Jyanling",
  "Dolakha, ",
  "Dukuchhap, ",
  "Dukuchhap, ChampiWard",
  "Duragau, Khatinga wards 4, 5, 6",
  "Fakhel, ",
  "Gairimudi, ",
  "Gakhu, Dandagaun",
  "Gati, ",
  "Gatlang, and Syafru VDC",
  "Gaunkharka, wards 1 to 9",
  "Gaurisankar, Sinigaun",
  "Gerkhu, wards 3, 4, 9",
  "Ghyalchok, Beni Gau ward 4",
  "Godawari, Kotgaun",
  "Godawari, ward",
  "Gokarneswor, Thali",
  "Gonggabu, ",
  "Gotikhel, ",
  "Gumdel, ",
  "Gumdel, Pekanas, Thado Khola, Koryam",
  "Gumdel, and BamtiBhandar - Bhanelar/Deurali/Lapchane/Thodung/Serding",
  "Gumdel, wards 1 to 9",
  "Gumdi, Jyamrung",
  "Hagam, ",
  "Hagam, Yanlakot",
  "Harisiddhi, ",
  "Hurnamadi, Phulbari and Ghadi",
  "Ikudol, ",
  "Jalbire, ",
  "Jalbire, Selang ward 4",
  "Jethal, Jethal wards 1, 2, 3",
  "Jethal, wards 1, 2, 3",
  "Jharlang, Sertung",
  "Jharuwarasi, and also Chapagaun",
  "Jibjibe(Nilkantha), Kalikastan",
  "Jorpati, ",
  "Jyamire, Rayale",
  "Jyamrung, Kuma",
  "Jyamrung, Nayagaun",
  "Kabhre Palanchok, ",
  "Kadambas, ",
  "Kadambas, Lapsey",
  "Kakani, Dovan",
  "Kakani, Ranipauwa",
  "Kakani, Wards 6, 8, 3",
  "Kaku, Babarka, Worwo",
  "KartikeDeurali, ",
  "KartikeDeurali, Bhanjyang",
  "KartikeDeurali, ward 4",
  "Katakuti, and also Bhusapheda VDC",
  "Katakuti, and also Bhusaphedi VDC",
  "KathmanduN.P., ",
  "KathmanduN.P., Balaju",
  "KathmanduN.P., Brikutimandap",
  "KathmanduN.P., Chamati",
  "KathmanduN.P., Chhetrapati",
  "KathmanduN.P., Dirghayu Guru Hospital and Research Center",
  "KathmanduN.P., Government hospitals in KTM, Bhaktapur and Lalitpur",
  "KathmanduN.P., Jyabahal",
  "KathmanduN.P., Kuleshwor",
  "KathmanduN.P., Maligoan",
  "KathmanduN.P., New Baneshwor - ward 10",
  "KathmanduN.P., Sapkota (?)",
  "KathmanduN.P., Swayambu Langtang Camp",
  "KathmanduN.P., Swayambu Langtang Camp (Yellow Gumba",
  "KathmanduN.P., Swayambu ward 15",
  "KathmanduN.P., Swayambunath",
  "KathmanduN.P., TU Teaching Hospital ICU",
  "KathmanduN.P., Temples around the KTM Valley",
  "Kautunje, Suryabinayak",
  "Kavrenityachandeswor, Badal Gaun",
  "Khokana, ",
  "Khokana, Karyabinayak",
  "KirtipurN.P., ",
  "KirtipurN.P., Itagol",
  "KirtipurN.P., Panga",
  "Lagarche, ",
  "Lakhanpur, ",
  "LakuriDada, Khari Dhurga",
  "LalitpurN.P., ",
  "Lamatar, Mahalaxmi Nagu",
  "Langtang, ",
  "Lapsephedi, ",
  "Lele, ",
  "Lele, Thapagaun",
  "Lisankhu, Wafal",
  "Lubhu, ",
  "Lubhu, and also Siddhipur VDC",
  "Machchhegaun, Dungetar village ward 7",
  "Machchhegaun, Sharmasthali",
  "MadhyapurThimiN.P., Nagadesh",
  "Mahakali, Nepane ward 9",
  "Mahankal, Sera",
  "Malta, ",
  "Marpak, ",
  "Marpak, Nimachok",
  "Marpak, Nirachowk",
  "Marpak, ward 5",
  "Mathurapatifulbari, Bukhil, Bhakundebesi, Khopase",
  "Nagarkot, Rohini, Chisapani, Bakhrigaun, Takurigaun",
  "Nala(Ugrachandi), Ugrachandi Nala",
  "Nalang, Pipal Nalang",
  "Nallu, Choughare",
  "Nankhel, Maligaun",
  "Okharpauwa, Kagatigaun",
  "Pagretar, ",
  "Pagretar, Swora, ward 6 & 7",
  "Palung, Thaka - wards 1 & 2",
  "PanautiN.P., ",
  "PanautiN.P., Khopasi",
  "Phulasi, and Chanakha VDC",
  "Puranojhangajholi, Khanikhadka",
  "RakhaBangdel, R.Maheswori, RakhaDipsung, Sungdel",
  "Ramche, Battay, ChamKharkay, Bhirkuna, Binday",
  "Ramkot, Nagarjun",
  "Raviopi, ",
  "Reegaun, Satya",
  "Sahare, ",
  "Sainbu, Pharsidol",
  "Salleri, Dudkunda Village",
  "Salyantar, ",
  "Sangachok, Jalkeni",
  "Sangachok, Jogitar",
  "Sangachok, Korchowk ward 4",
  "Sangachok, Panichaur",
  "Sangkosh, Apswara",
  "Sankhu, ",
  "Shreenathkot, Hansapur",
  "Sikre, ",
  "Sikre, Baskote Gaun",
  "Sindhupalchok, ",
  "Sindhupalchok, and also Nuwakot district",
  "Sindhupalchok, different villages in Ramechhap, Dolakha, Okhaldhunga",
  "Sipadol, Naichal",
  "Sipadol, Soche",
  "Sipapokhare, ",
  "Sitapaila, Alegaun",
  "Sotang, and also Gudel and Chheskam VDCs",
  "Sundarijal, Sundarijal, Okhreni, Chilaunegaun - ward 6",
  "Suri, and also Lamabagar District",
  "Takasindu, Nunthala",
  "Takukot, ",
  "Takumajhalakuribot, Lakuri",
  "Tandrang, ",
  "Tandrang, Darme",
  "Tandrang, Darme ward 7",
  "Taple, and also Masel, Baguwa, Dhawa, Boralang",
  "Thakani, Ningale Village",
  "Thampal Chhap, Dhap",
  "Thanapati, ",
  "Thankot, Matshya",
  "Those, and also Khimti VDC",
  "ThuloDhading, KhaniDhading",
  "ThuloDhading, Tandi (7) and Bersma (9)",
  "ThuloPakhar, and also Jethal VDC",
  "Thumi, ",
  "Thumpakhar, Mesida",
  "Timure, and also Bridhim VDC",
  "Tupche, Mahadev Khadka, ward 7",
  "Yamunadanda, Simpani",
  "Yarsa, Arukharka"
];
